Update Rollout and Date targeting
bucketeer-io/bucketeer-docs pull request #36
Opened 2023-12-15 12:47 UTC by heitortessaro

2023-12-18 06:28 UTC, cre8ivejp commented on docs/feature-flags/creating-feature-flags/auto-operation/rollout.mdx
> +When you choose to use the rollout option, you are selecting an enabling operation from the [Auto Operation](/feature-flags/creating-feature-flags/auto-operation). That means that you will choose the
```suggestion
When you use the rollout option, you select an enabling operation from the [Auto Operation](/feature-flags/creating-feature-flags/auto-operation). That means that you will choose the flag variation that more users will receive as time goes on and the rollout approaches its end.
```

2023-12-18 06:28 UTC, cre8ivejp commented on docs/feature-flags/creating-feature-flags/auto-operation/rollout.mdx
> +Another important point related to the Manual option is that you don't need to reach 100% to submit the rollout. Supose the last entry to the Manual configuration is 90%. In this case, the rollout wi
```suggestion
Another important point related to the Manual option is that you don't need to reach 100% to submit the rollout. Suppose the last entry to the Manual configuration is 90%. In this case, the rollout will be concluded, and only 90% of your users will have access to the new variation. The remaining 10% will continue receiving the [off variation](/feature-flags/creating-feature-flags/targeting#the-targeting-page), the same as before the rollout.
```

2024-02-01 04:07 UTC, cre8ivejp requested changes

2024-02-01 04:07 UTC, cre8ivejp commented on docs/feature-flags/creating-feature-flags/auto-operation/rollout.mdx
> +The Progressive Rollout solution automates the release process of new features to your users by gradually providing the flag variation you choose as the [default strategy](/feature-flags/creating-fea
```suggestion
The Progressive Rollout solution automates the release process of new features to your users by gradually providing the flag variation you choose as the [default strategy](/feature-flags/creating-feature-flags/targeting) to a larger percentage of your users. This approach helps you detect problems early on and reduce the impact.
```

2024-02-01 04:07 UTC, cre8ivejp commented on docs/feature-flags/creating-feature-flags/auto-operation/rollout.mdx
> +You need to set two variation flags to use the rollout feature. For example, consider that you have a boolean flag with two variations: `true` and `false`. This flag determines whether new content is
```suggestion
The flag must have **two variations** to use the rollout feature. For example, consider that you have a boolean flag with two variations: `true` and `false`. This flag determines whether new content is available to users or not. 

Currently, the `false` variation is the [OFF variation](/feature-flags/creating-feature-flags/targeting#the-targeting-page), meaning users can't see the new content. However, you want to make the content available to all users within ten days. In this case, you can use the rollout feature to progressively roll out the `true` variation to 10% of your users daily. 
```

2024-02-02 13:28 UTC, heitortessaro commented on docs/feature-flags/creating-feature-flags/auto-operation/rollout.mdx
> +The Progressive Rollout solution automates the release process of new features to your users by gradually providing the flag variation you choose as the [default strategy](/feature-flags/creating-fea
Done

2024-02-02 13:28 UTC, heitortessaro commented on docs/feature-flags/creating-feature-flags/auto-operation/rollout.mdx
> +You need to set two variation flags to use the rollout feature. For example, consider that you have a boolean flag with two variations: `true` and `false`. This flag determines whether new content is
Done

2024-02-02 13:30 UTC, heitortessaro commented on docs/feature-flags/creating-feature-flags/auto-operation/rollout.mdx
> +6. Click **Submit**.
@cre8ivejp, Should I delete steps from 3 to 6?

2024-02-02 13:32 UTC, heitortessaro commented on docs/feature-flags/creating-feature-flags/auto-operation/rollout.mdx
> +If a progressive rollout is created for a disabled flag, the progressive rollout automatically enables the flags as soon as it starts. The progressive rollout can only enable a flag once, when it sta
Done

2024-02-02 13:33 UTC, heitortessaro commented on docs/feature-flags/creating-feature-flags/auto-operation/rollout.mdx
> +If a flag with an active progressive rollout is turned OFF, the system will automatically stop the progressive rollout.
Done

2024-02-02 13:34 UTC, heitortessaro commented on docs/feature-flags/creating-feature-flags/auto-operation/rollout.mdx
> +Editing a running progressive rollout is not supported in Bucketeer. You can remove or stop the rollout.
Done

2024-02-02 13:34 UTC, heitortessaro commented on docs/feature-flags/creating-feature-flags/auto-operation/rollout.mdx
> +If you remove the rollout, no historical data will be stored. Only logs will report the operations related to that rollout.
Done

2024-02-02 13:35 UTC, heitortessaro commented on docs/feature-flags/creating-feature-flags/auto-operation/rollout.mdx
> +When you stop the rollout, it's shut, moving it to the finished tab, where you can inspect the rollout level it reached, for example.
Done

2024-02-02 13:35 UTC, heitortessaro commented on docs/feature-flags/creating-feature-flags/auto-operation/rollout.mdx
> +When you stop the rollout, it's shut, moving it to the finished tab, where you can inspect the rollout level it reached, for example.
Done

2024-02-02 13:35 UTC, heitortessaro commented on docs/feature-flags/creating-feature-flags/auto-operation/rollout.mdx
> +### Operational rules
Done

2024-02-02 13:36 UTC, heitortessaro commented on docs/feature-flags/creating-feature-flags/auto-operation/rollout.mdx
> +Progressive rollouts can be created for flags, whether they're enabled or disabled. If a progressive rollout is created for a disabled flag, the progressive rollout will automatically enable the flag
Done

2024-02-02 13:37 UTC, heitortessaro commented on docs/feature-flags/creating-feature-flags/auto-operation/rollout.mdx
> +The progressive rollout is designed to work exclusively with flags having two variations. If you try to use it with a flag with more variations, you'll receive an error message during the progressive
Done

2024-02-02 13:37 UTC, heitortessaro commented on docs/feature-flags/creating-feature-flags/auto-operation/rollout.mdx
> +If you create a progressive rollout and the flag default strategy uses a [rollout percentage](/feature-flags/creating-feature-flags/targeting#rollout-percentage), the existing rollout rules will be r
Done

2024-02-02 13:37 UTC, heitortessaro commented on docs/feature-flags/creating-feature-flags/auto-operation/rollout.mdx
> +It's vital to notice that executing a Kill Switch, triggered by schedule or event rate conditions, has higher priority than the progressive rollout. Therefore, if your flag has a running progressive
Done

2024-02-02 13:38 UTC, heitortessaro commented on docs/feature-flags/creating-feature-flags/auto-operation/rollout.mdx
> +- **Variation**: Choose the variation to roll out. You should not choose the same variation selected as [OFF variation](/feature-flags/creating-feature-flags/targeting#the-targeting-page). Otherwise,
Done

2024-02-02 13:38 UTC, heitortessaro commented on docs/feature-flags/creating-feature-flags/auto-operation/rollout.mdx
> +- **Variation**: Choose the variation to roll out. You should not choose the same variation selected as [OFF variation](/feature-flags/creating-feature-flags/targeting#the-targeting-page). Otherwise,
Done

2024-02-02 13:39 UTC, heitortessaro commented on docs/feature-flags/creating-feature-flags/auto-operation/rollout.mdx
> +The progressive rollout only works for flags with two variations.
Done

2024-02-02 13:39 UTC, heitortessaro commented on docs/feature-flags/creating-feature-flags/auto-operation/rollout.mdx
> +1. Go to the **Auto Operation** page.
Done

2024-02-02 13:40 UTC, heitortessaro commented on docs/feature-flags/creating-feature-flags/auto-operation/rollout.mdx
> +3. The operation setting panel will appear. Choose the **Enable** operation.
Done

2024-02-02 13:40 UTC, heitortessaro commented on docs/feature-flags/creating-feature-flags/auto-operation/rollout.mdx
> +4. Select **Progreesive Rollout**.
Done

2024-02-02 13:40 UTC, heitortessaro commented on docs/feature-flags/creating-feature-flags/auto-operation/rollout.mdx
> +6. Click **Submit**.
Done

2024-02-02 13:41 UTC, heitortessaro commented on docs/feature-flags/creating-feature-flags/auto-operation/rollout.mdx
> +Using the Manual rollout, you do not need to follow an incremental rule for each rollout phase. The only restriction is that each new rollout phase must have a higher weight than the previous one.
Done

2024-02-02 14:59 UTC, cre8ivejp commented on docs/feature-flags/creating-feature-flags/auto-operation/rollout.mdx
> +If the flag is disabled when a progressive rollout is created, the progressive rollout automatically enables the flag as soon as it starts. The progressive rollout can only enable a flag once when it
```suggestion
If the flag is disabled when a progressive rollout is created, the progressive rollout automatically enables the flag as soon as it starts.
```

2024-02-02 16:43 UTC, cre8ivejp commented on docs/feature-flags/creating-feature-flags/auto-operation/rollout.mdx
> +The progressive rollout is designed to work exclusively with flags having two variations.
```suggestion
The progressive rollout is designed to work exclusively with flags having two variations and no running experiment.
```

2024-02-02 16:43 UTC, cre8ivejp commented on docs/feature-flags/creating-feature-flags/auto-operation/rollout.mdx
> +:::caution Number of variations
```suggestion
:::caution Restrictions
```

2024-02-02 16:43 UTC, cre8ivejp commented on docs/feature-flags/creating-feature-flags/auto-operation/rollout.mdx
> +The progressive rollout only works for flags with **two variations**.
The progressive rollout only works for flags with **two variations** and **no running experiment**.

2024-02-02 16:45 UTC, cre8ivejp commented on docs/feature-flags/creating-feature-flags/auto-operation/rollout.mdx
> +:::caution Disabled Flag behaviour
```suggestion
:::info Disabled Flag behaviour
```

2024-02-28 02:40 UTC, cre8ivejp approved these changes
Thank you!

2024-02-28 02:41 UTC, merged